#!/bin/bash

tput setaf 7 ; tput setab 4 ; tput bold ; printf '%20s%s\n' "ㅤ🐉ㅤChange Limit on Simultaneous Connectionsㅤ🐉ㅤ" ; tput sgr0

database="/root/usuarios.db"

if [ ! -f "$database" ]; then
	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "File $database not found!" ; echo "" ; tput sgr0
	exit 1
else
	tput setaf 3 ; tput bold ; echo ""; echo "◇ LIST OF USERS AND THEIR LIMITS:" ; tput sgr0
	echo ""
	_userT=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody)
	i=0
	unset _userPass
	while read -r _user; do
		i=$((i + 1))
		_oP=$i
		[[ $i -lt 10 ]] && _oP="0$i"
		limit=$(grep -w "$_user" "$database" | cut -d' ' -f2)
		lim=$(echo -e "\033[1;33m◇ㅤLimit\033[1;37m: $limit")
		printf '%-65s%s\n' "\033[1;31m[\033[1;36m$_oP\033[1;31m] \033[1;37m- \033[1;32m$_user\033[0m" "$lim"
		_userPass+="${_oP}:${_user}\n"
	done <<< "$_userT"
	echo ""
	num_user=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
	read -p "$(tput setaf 2)◇ Enter or select a user $(tput setaf 3)[1-$(tput setaf 6)$num_user$(tput setaf 3)]: " option

	usuario=$(echo -e "${_userPass}" | grep -E "\b$option\b" | cut -d: -f2)

	if [[ -z $option || -z $usuario ]]; then
		tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "◇ Empty or non-existent user" ; echo "" ; tput sgr0
		exit 1
	fi

	if ! cat /etc/passwd | grep -w "$usuario" > /dev/null; then
		tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "◇ The user $usuario was not found" ; echo "" ; tput sgr0
		exit 1
	fi

	echo -ne "\n\033[1;32m◇ New limit for the user \033[1;33m$usuario\033[1;37m: "
	read sshnum

	if [[ -z $sshnum || ! $sshnum =~ ^[0-9]+$ || $sshnum -lt 1 ]]; then
		tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "◇ You must enter a valid number greater than zero!" ; echo "" ; tput sgr0
		exit 1
	fi

	grep -v "^$usuario[[:space:]]" "/root/usuarios.db" > /tmp/a
	mv /tmp/a "/root/usuarios.db"
	echo "$usuario $sshnum" >> "/root/usuarios.db"

	tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "◇ Limit applied to the user $usuario was $sshnum" ; tput sgr0
	sleep 2
	exit 0
fi
