#!/bin/bash

clear

local="/etc/bannerssh"
chk=$(grep -E '^[[:space:]]*Banner' /etc/ssh/sshd_config)

if [[ $(netstat -nltp | grep 'dropbear' | wc -l) -ne 0 ]]; then
    [[ $(grep -wc "$local" /etc/default/dropbear) -eq 0 ]] && echo "DROPBEAR_BANNER=\"$local\"" >> /etc/default/dropbear
fi

if [[ -z "$chk" ]]; then
    [[ $(grep -wc "$local" /etc/ssh/sshd_config) -eq 0 ]] && echo "Banner $local" >> /etc/ssh/sshd_config
else
    local=$(echo "$chk" | awk '{print $2}')
fi

echo -e "\E[44;1;37m     ㅤ🐉ㅤBANNER MANAGERㅤ🐉ㅤ        \E[0m"
echo ""
echo -e "\033[1;32m◇───MANUAL BANNER ADDING METHOD───◇"
echo -e "\033[1;37m◇ Step 1:- Press CTRL+C and send  👇"
echo -e "\033[1;31msudo nano /etc/bannerssh"
echo -e "\033[1;37m◇ PASTE YOUR BANNER AS HTML TEXT"
echo -e "\033[1;37m◇ Step 2:- Press CTRL+O enter CTRL+X"
echo ""
echo -e "\033[1;32m Or"
echo ""
echo -e "\033[1;32m◇───EASY BANNER ADDING METHOD───◇"
echo -e "\033[1;31m[\033[1;36m1\033[1;31m]\033[1;37m • \033[1;33mADD BANNER"
echo -e "\033[1;31m[\033[1;36m2\033[1;31m]\033[1;37m • \033[1;33mREMOVE BANNER"
echo -e "\033[1;31m[\033[1;36m3\033[1;31m]\033[1;37m • \033[1;33mCOME BACK"
echo ""

read -rp "◇ WHAT DO YOU WANT TO DO ? : " resp

if [[ "$resp" = "1" ]]; then
    echo ""
    read -rp "◇ WHICH MESSAGE DO YOU WANT TO DISPLAY ? : " msg1

    if [[ -z "$msg1" ]]; then
        echo -e "\n\033[1;31m◇ Empty or invalid field!\033[0m"
        sleep 2
        banner
    fi

    echo -e "\n\033[1;31m[\033[1;36m01\033[1;31m]\033[1;33m SMALL FONT SIZE"
    echo -e "\033[1;31m[\033[1;36m02\033[1;31m]\033[1;33m AVERAGE FONT SIZE"
    echo -e "\033[1;31m[\033[1;36m03\033[1;31m]\033[1;33m LARGE FONT SIZE"
    echo -e "\033[1;31m[\033[1;36m04\033[1;31m]\033[1;33m GIANT FONT SIZE"
    echo ""
    read -rp "◇ WHAT IS THE FONT SIZE ? : " opc

    case $opc in
        "1" | "01") _size='6' ;;
        "2" | "02") _size='4' ;;
        "3" | "03") _size='3' ;;
        "4" | "04") _size='1' ;;
        *) _size='4' ;;
    esac

    echo -e "\n\033[1;31m[\033[1;36m01\033[1;31m]\033[1;33m BLUE"
    echo -e "\033[1;31m[\033[1;36m02\033[1;31m]\033[1;33m GREEN"
    echo -e "\033[1;31m[\033[1;36m03\033[1;31m]\033[1;33m RED"
    echo -e "\033[1;31m[\033[1;36m04\033[1;31m]\033[1;33m YELLOW"
    echo -e "\033[1;31m[\033[1;36m05\033[1;31m]\033[1;33m PINK"
    echo -e "\033[1;31m[\033[1;36m06\033[1;31m]\033[1;33m CYAN"
    echo -e "\033[1;31m[\033[1;36m07\033[1;31m]\033[1;33m ORANGE"
    echo -e "\033[1;31m[\033[1;36m08\033[1;31m]\033[1;33m PURPLE"
    echo -e "\033[1;31m[\033[1;36m09\033[1;31m]\033[1;33m BLACK"
    echo -e "\033[1;31m[\033[1;36m10\033[1;31m]\033[1;33m NO COLOR"
    echo ""
    read -rp "◇ WHAT'S THE COLOR ? : " ban_cor

    case $ban_cor in
        "1" | "01") echo "<h$_size><font color='blue'>$msg1" >> "$local" ;;
        "2" | "02") echo "<h$_size><font color='green'>$msg1" >> "$local" ;;
        "3" | "03") echo "<h$_size><font color='red'>$msg1" >> "$local" ;;
        "4" | "04") echo "<h$_size><font color='yellow'>$msg1" >> "$local" ;;
        "5" | "05") echo "<h$_size><font color='#F535AA'>$msg1" >> "$local" ;;
        "6" | "06") echo "<h$_size><font color='cyan'>$msg1" >> "$local" ;;
        "7" | "07") echo "<h$_size><font color='#FF7F00'>$msg1" >> "$local" ;;
        "8" | "08") echo "<h$_size><font color='#9932CD'>$msg1" >> "$local" ;;
        "9" | "09") echo "<h$_size><font color='black'>$msg1" >> "$local" ;;
        "10") echo "<h$_size>$msg1</h$_size>" >> "$local" ;;
        *) echo "<h$_size><font color='green'>$msg1" >> "$local" ;;
    esac

    echo "</font></h$_size>" >> "$local"
    service ssh restart > /dev/null 2>&1 && service dropbear restart > /dev/null 2>&1
    echo -e "\n\033[1;32m◇ BANNER ADDED!\033[0m"
    sleep 2
    unset ban_cor

elif [[ "$resp" = "2" ]]; then
    echo " " > "$local"
    echo -e "\n\033[1;32m◇ BANNER DELETED!\033[0m"
    service ssh restart > /dev/null 2>&1 && service dropbear restart > /dev/null 2>&1
    sleep 2
    menu
elif [[ "$resp" = "3" ]]; then
    menu
else
    echo -e "\n\033[1;31m◇ Invalid option!\033[0m"
    sleep 2
    banner
fi
