#!/bin/bash

database="/root/usuarios.db"

if [ ! -f "$database" ]; then
    echo "◇ File /root/usuarios.db not found"
    exit 1
fi

get_dropbear_users() {
    log="/var/log/auth.log"
    loginsukses='Password auth succeeded'
    port_dropbear=$(ps aux | grep dropbear | awk NR==1 | awk '{print $17}')
    pids=$(ps ax | grep "dropbear" | grep "$port_dropbear" | awk -F" " '{print $1}')

    for pid in $pids; do
        pidlogs=$(grep "$pid" "$log" | grep "$loginsukses" | awk -F" " '{print $3}')
        i=0

        for pidend in $pidlogs; do
            let i=i+1
        done

        if [ "$pidend" ]; then
            login=$(grep "$pid" "$log" | grep "$pidend" | grep "$loginsukses")
            PID=$pid
            user=$(echo "$login" | awk -F" " '{print $10}' | sed -r "s/'/ /g")
            waktu=$(echo "$login" | awk -F" " '{print $2"-"$1,$3}')

            printf "%-27s%-15s%s\n" "$user" "$i" "$waktu"
        fi
    done
}

while true; do
    clear
    echo -e "\E[42;1;37m            ㅤ🐉ㅤDROPBEAR LIMITERㅤ🐉ㅤ             \E[0m"
    echo -e "\E[42;1;37m◇User                          ◇Connection¦Limit\E[0m"

    while read -r usline; do
        user=$(echo "$usline" | cut -d' ' -f1)
        s2ssh=$(echo "$usline" | cut -d' ' -f2)
        s3drop=$(get_dropbear_users | grep "$user" | wc -l)

        if [ -z "$user" ]; then
            continue
        fi

        tput setaf 3 ; tput bold ; printf '  %-35s%s\n' "$user" "$s3drop/$s2ssh"; tput sgr0

        if [ "$s3drop" -gt "$s2ssh" ]; then
            echo -e "\E[41;1;37m◇ User disconnected for exceeding the limit! \E[0m"
            while read -r line; do
                tmp=$(echo "$line" | cut -d' ' -f1)
                kill "$tmp"
            done < <(echo "$usline" | awk '{print $2}' | cut -d' ' -f2)
        fi
    done < "$database"

    sleep 6
done
