#!/bin/bash
clear

if [[ ! -d /usr/share/.hehe ]]; then
    echo "Error: Directory '/usr/share/.hehe' not found. Exiting..."
    exit 1
fi

install_squid3() {
    if [[ ! -e /etc/apt/sources.list.d/trusty_sources.list ]]; then
        touch /etc/apt/sources.list.d/trusty_sources.list >/dev/null 2>&1
        echo "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe" | tee --append /etc/apt/sources.list.d/trusty_sources.list >/dev/null 2>&1
    fi

    if [[ $(grep -wc 'Debian' /etc/issue.net) != '0' ]]; then
        apt install dirmngr -y >/dev/null 2>&1
        if [[ $(apt-key list 2>/dev/null | grep -c 'Ubuntu') == '0' ]]; then
            apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32 >/dev/null 2>&1
        fi
    fi

    apt update -y >/dev/null 2>&1
    apt install squid3=3.3.8-1ubuntu6 squid=3.3.8-1ubuntu6 squid3-common=3.3.8-1ubuntu6 -y >/dev/null 2>&1
    wget -qO- https://raw.githubusercontent.com/Drlaravel/DRAGON-VPS-MANAGER-v2/main/Install/squid3 >/etc/init.d/squid3
    chmod +x /etc/init.d/squid3 >/dev/null 2>&1
    update-rc.d squid3 defaults >/dev/null 2>&1
}

remove_squid3() {
    if [[ -e /etc/apt/sources.list.d/trusty_sources.list ]]; then
        rm /etc/apt/sources.list.d/trusty_sources.list >/dev/null 2>&1
        if [[ $(grep -wc 'Debian' /etc/issue.net) != '0' ]]; then
            apt-key del 3B4FE6ACC0B21F32 >/dev/null 2>&1
        fi
        apt remove squid3=3.3.8-1ubuntu6 squid=3.3.8-1ubuntu6 squid3-common=3.3.8-1ubuntu6 -y >/dev/null 2>&1
        apt update -y >/dev/null 2>&1
        apt autoremove -y >/dev/null 2>&1
    fi
}

if [[ $op == '1' ]]; then
    install_squid3
    echo "Squid3 installed successfully!"
else
    remove_squid3
    echo "Squid3 removed successfully!"
fi
