#!/bin/bash

function print_header() {
    tput setaf 7; tput setab 4; tput bold; printf '%33s%s%-12s\n' "🐉ㅤ📅ㅤchange expiry dateㅤ📅ㅤ🐉"; tput sgr0
    echo ""
}

function print_user_list() {
    echo -e "\033[1;33m◇ LIST OF USERS AND EXPIRY DATE:\033[0m "
    echo ""
    tput setaf 7; tput bold

    database="/root/usuarios.db"
    list_user=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody)
    i=0
    unset _userPass

    while read user; do
        i=$((i + 1))
        _oP=$i
        [[ $i -lt 10 ]] && i="0$i"
        expire="$(chage -l "$user" | grep -E "Account expires" | cut -d ' ' -f3-)"
        # Rest of the logic here
        # ...
    done <<< "${list_user}"

    tput sgr0
    echo ""
}

function get_user_input() {
    num_user=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
    echo -ne "\033[1;32m◇ㅤEnter or select a user \033[1;33m[\033[1;36m1\033[1;33m-\033[1;36m$num_user\033[1;33m]\033[1;37m: "
    read -r option

    if [[ -z $option ]]; then
        echo ""
        tput setaf 7; tput setab 1; tput bold; echo "◇ㅤError, Empty or Invalid Username! "; tput sgr0
        exit 1
    fi

    usuario=$(echo -e "${_userPass}" | grep -E "\b$option\b" | cut -d: -f2)
    # Rest of the logic here
    # ...
}

print_header
print_user_list
get_user_input
