#!/bin/bash

clear

fun_prog() {
    local cmd=$1
    $cmd > /dev/null 2>&1 &
    tput civis
    echo -ne "\033[1;32m.\033[1;33m.\033[1;31m. \033[1;32m"
    while [ -d /proc/$! ]; do
        for i in / - \\ \|; do
            sleep .1
            echo -ne "\e[1D$i"
        done
    done
    tput cnorm
    echo -e "\e[1DOK"
}

restart_service() {
    local service_name=$1
    if [[ $(systemctl is-active $service_name) == "active" ]]; then
        echo -ne "\033[1;33m◇ RESTARTING $service_name "; fun_prog "service $service_name restart"
        echo ""
        sleep 1
    fi
}

services=("ssh" "squid" "squid3" "stunnel4" "dropbear" "openvpn" "apache2")

for service in "${services[@]}"; do
    if command -v "$service" &> /dev/null; then
        restart_service "$service"
    fi
done

echo -e "\033[1;32m◇ SERVICES RESTARTED SUCCESSFULLY!\033[0m"
sleep 1
